source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

inhibit_all_warnings!

target 'Autopia' do
    pod 'SnapKit', '~> 0.15.0'
    pod 'SDWebImage', '~> 3.7.5'
    pod 'pop', '~> 1.0'
    pod 'Shimmer'
    pod 'Charts'
    pod 'SCLAlertView'
    pod 'MagicalRecord'
    pod 'SwiftDate'
    pod 'ZCAnimatedLabel'
    pod 'BTNavigationDropdownMenu'
end