# Uncomment this line to define a global platform for your project
# Uncomment this line if you're using Swift
# source 'https://github.com/CocoaPods/Specs.git'
# platform :ios, '8.0'
use_frameworks!

target 'Carols' do
pod 'SnapKit', '~> 0.15.0'
pod 'SwiftyBeaver'
pod 'PageMenu'
pod 'SlideMenuControllerSwift'
pod 'CocoaAsyncSocket'
pod 'Alamofire', '~> 3.3'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'MagicalRecord'
pod 'SDWebImage', '~>3.7'
pod 'SVProgressHUD'
pod 'Mantle'
pod 'NAKPlaybackIndicatorView'
pod 'CustomIOSAlertView'
pod 'PKHUD'
pod 'SDCycleScrollView'
#第三方登录
# 主模块(必须)
pod 'ShareSDK3'
# Mob 公共库(必须) 如果同时集成SMSSDK iOS2.0:可看此注意事项：http://bbs.mob.com/thread-20051-1-1.html
pod 'MOBFoundation'
# UI模块(非必须，需要用到ShareSDK提供的分享菜单栏和分享编辑页面需要以下1行)
pod 'ShareSDK3/ShareSDKUI'
# 平台SDK模块(对照一下平台，需要的加上。如果只需要QQ、微信、新浪微博，只需要以下3行)
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
end

target 'CarolsTests' do

end

target 'CarolsUITests' do

end

